// @flow

import { type TwitchClip } from './getClips';

export default function buildDescription(
  configuration: $FlowFixMe,
  clips: Array<TwitchClip>,
  elapsedTime: number,
): string {
  const minutes = Number((elapsedTime / 60).toFixed(0));
  const seconds = Number((elapsedTime % 60).toFixed(0));

  return `This video is generated by node.js application!

--Details--
Clips: ${configuration.size}
Period: ${configuration.period}
Language: ${configuration.language}
Trending: ${configuration.trending ? 'true' : 'false'}
Game: ${configuration.game || 'Not Specified'}
Generated in ${minutes < 10 ? `0${minutes}` : minutes}:${
    seconds < 10 ? `0${seconds}` : seconds
  } minutes.

--References--
${clips
    .map(
      (clip, index) => `
--Clip ${index + 1}--
| Title: ${clip.title}
| Game: ${clip.game}
| Streamer: ${clip.broadcaster.channel_url}`,
    )
    .join('\n')}`;
}
