// @flow

import { type TwitchClip } from './getClips';

export default function buildDescription(
  configuration: $FlowFixMe,
  clips: Array<TwitchClip>,
  elapsedTime: number,
): string {
  return `This video is generated by node.js application!

--Details--
Clips: ${configuration.size}
Period: ${configuration.period}
Language: ${configuration.language}
Trending: ${configuration.trending ? 'true' : 'false'}
Game: ${configuration.game || 'Not Specified'}
Generated in ${(elapsedTime / 60).toFixed(0)}:${(elapsedTime % 60).toFixed(0)} minutes.

--References--
${clips
    .map(
      (clip, index) => `
--Clip ${index + 1}--
| Title           : ${clip.title}
| Game            : ${clip.game}
| Views           : ${clip.views}
| Streamer        : ${clip.broadcaster.display_name}
| Streamer Channel: ${clip.broadcaster.channel_url}
| Curator         : ${clip.curator.display_name}
| Curator Channel : ${clip.curator.channel_url}`,
    )
    .join('\n')}`;
}
